CREATE TABLE USER (
NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
ENC_PASSW VARCHAR(30) NOT NULL,
ID VARCHAR(36) PRIMARY KEY,
CREATED DATE NOT NULL,
MODIFIED DATE,
LAST_LOGIN DATE NOT NULL,
IS_ACTIVE BOOLEAN NOT NULL);

CREATE TABLE PHONE (
ID VARCHAR(36) PRIMARY KEY,
NUMBER VARCHAR(15) NOT NULL,
CITY_CODE VARCHAR(5) NOT NULL,
COUNTRY_CODE VARCHAR(3) NOT NULL,
ID_USER VARCHAR(36) NOT NULL,
FOREIGN KEY (ID_USER) REFERENCES USER(ID));